In [2]:
import os
import pandas as pd

from src.utils import get_base_dir

In [3]:
dataset = "dooway"
region = "EmiliaRomagna" #"Basilicata" #
region_str = "emilia_romagna" #region.lower() #
base_dir = os.path.join(get_base_dir(), dataset, region)
dir_in = os.path.join(base_dir, "raw_data")
nodes_dir = os.path.join(base_dir, "original_data", "nodes")
edges_dir = os.path.join(base_dir, "original_data", "edges")

BASILICATA

NODES

In [3]:
df = pd.read_parquet(os.path.join(dir_in, f"category_{region_str}.parquet")) 
# df.shape (1525, 2)
df.head()

   unique_id                        category
0          1                    cycling_park
1          2  solar_photovoltaic_power_plant
2          3                      art_center
3          4             electronics_company
4          5          natural_history_museum

In [4]:
df["unique_id"] = df["unique_id"].apply(lambda x: x - 1)
df.to_parquet(os.path.join(nodes_dir, "category.parquet"))
df.head()

   unique_id                        category
0          0                    cycling_park
1          1  solar_photovoltaic_power_plant
2          2                      art_center
3          3             electronics_company
4          4          natural_history_museum

In [5]:
df = pd.read_parquet(os.path.join(dir_in, f"poi_{region_str}.parquet")) 
df.head()

,index,type,rank_group,rank_absolute,domain,title,url,contact_url,rating,hotel_rating,...,local_justifications,is_directory_item,contributor_url,region,reviews,sentiment,industry,custom_category,unique_id,main_image_embedding
0,0,restaurants,1,1,None,L'Antico Borgo,None,None,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,None,False,None,basilicata,NaN,NaN,NaN,NaN,1,"[-0.19753423, 0.22135854, 0.1589038, -0.080560..."
1,1,restaurants,2,2,www.chin-up.it,"Chin Up! ""Al nido del falco""",http://www.chin-up.it/,None,"{'rating_type': 'Max5', 'value': 4.7, 'votes_c...",NaN,...,None,False,https://maps.google.com/maps/contrib/100396939...,basilicata,NaN,NaN,NaN,NaN,2,"[0.46170676, 0.29732698, 0.17882484, -0.351835..."
2,2,restaurants,3,3,None,Antico borgo di Stolfi Angelo,None,None,"{'rating_type': 'Max5', 'value': 4.5, 'votes_c...",NaN,...,None,False,https://maps.google.com/maps/contrib/104704191...,basilicata,NaN,NaN,NaN,NaN,3,"[-0.031655762, 0.32317862, -0.25760216, 0.0752..."
3,3,restaurants,4,4,None,Central Bar Pub,None,None,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,None,False,https://maps.google.com/maps/contrib/108493660...,basilicata,NaN,NaN,NaN,NaN,4,"[-0.14220355, -0.040702403, -0.09907015, -0.24..."
4,4,restaurants,5,5,www.hotelsellata.it,Hotel Sellata,http://www.hotelsellata.it/,None,"{'rating_type': 'Max5', 'value': 3.8, 'votes_c...",3.0,...,"[{'type': 'user_review', 'text': '""Ottimo post...",False,None,basilicata,NaN,NaN,NaN,NaN,5,None

In [6]:
df["unique_id"] = df["unique_id"].apply(lambda x: x - 1)
df.to_parquet(os.path.join(nodes_dir, "poi.parquet"))
# df.shape (14853, 35) --- to drop: REVIEWS, SENTIMENT, INDUSTRY, CUSTOM_CATEGORY
df.head()

,index,type,rank_group,rank_absolute,domain,title,url,contact_url,rating,hotel_rating,...,local_justifications,is_directory_item,contributor_url,region,reviews,sentiment,industry,custom_category,unique_id,main_image_embedding
0,0,restaurants,1,1,None,L'Antico Borgo,None,None,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,None,False,None,basilicata,NaN,NaN,NaN,NaN,0,"[-0.19753423, 0.22135854, 0.1589038, -0.080560..."
1,1,restaurants,2,2,www.chin-up.it,"Chin Up! ""Al nido del falco""",http://www.chin-up.it/,None,"{'rating_type': 'Max5', 'value': 4.7, 'votes_c...",NaN,...,None,False,https://maps.google.com/maps/contrib/100396939...,basilicata,NaN,NaN,NaN,NaN,1,"[0.46170676, 0.29732698, 0.17882484, -0.351835..."
2,2,restaurants,3,3,None,Antico borgo di Stolfi Angelo,None,None,"{'rating_type': 'Max5', 'value': 4.5, 'votes_c...",NaN,...,None,False,https://maps.google.com/maps/contrib/104704191...,basilicata,NaN,NaN,NaN,NaN,2,"[-0.031655762, 0.32317862, -0.25760216, 0.0752..."
3,3,restaurants,4,4,None,Central Bar Pub,None,None,"{'rating_type': 'Max5', 'value': 4.6, 'votes_c...",NaN,...,None,False,https://maps.google.com/maps/contrib/108493660...,basilicata,NaN,NaN,NaN,NaN,3,"[-0.14220355, -0.040702403, -0.09907015, -0.24..."
4,4,restaurants,5,5,www.hotelsellata.it,Hotel Sellata,http://www.hotelsellata.it/,None,"{'rating_type': 'Max5', 'value': 3.8, 'votes_c...",3.0,...,"[{'type': 'user_review', 'text': '""Ottimo post...",False,None,basilicata,NaN,NaN,NaN,NaN,4,None

In [8]:
df.columns

Index(['index', 'type', 'rank_group', 'rank_absolute', 'domain', 'title',
       'url', 'contact_url', 'rating', 'hotel_rating', 'price_level',
       'rating_distribution', 'address', 'address_info', 'place_id',
       'main_image', 'total_photos', 'category', 'additional_categories',
       'category_ids', 'work_hours', 'feature_id', 'cid', 'latitude',
       'longitude', 'is_claimed', 'local_justifications', 'is_directory_item',
       'region', 'contributor_url', 'unique_id', 'main_image_embedding'],
      dtype='object')

In [7]:
df = pd.read_parquet(os.path.join(dir_in, f"review_{region_str}.parquet")) 
df.head()

,cid,place_id,location_code,type,datetime,profile_url,review_text,timestamp,rating_value,reviews_count,photos_count,local_guide,review_highlights,unique_id,review_text_embedding
0,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,QA1VvS65a3xuYX49qQU2BS1hwqjKID2+kqPadWT8oL8=,Paese di montagna con boschi di faggi e castag...,2020-12-04 10:39:16 +00:00,4.0,100.0,274.0,True,None,1,"[-0.02132909931242466, 0.0855952724814415, 0.0..."
1,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LTZBZHp0ee1g8sWcfwl9CZRctKfoLkNRbtGlbZCDe08=,"Paese caratteristico con tanto da visitare,il ...",2021-12-04 10:39:16 +00:00,5.0,11.0,115.0,True,None,2,"[0.11749532073736191, 0.027359535917639732, 0...."
2,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,Tn9Bq3/3GlLrDgcsZ7AgQk9X9oYPR6pSBzYZpiIjm7E=,Concerto Gospel del 23/12/2021\nOrganizzato da...,2022-12-04 10:39:16 +00:00,5.0,18.0,33.0,True,None,3,"[-0.0026724785566329956, 0.1681678593158722, 0..."
3,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,5gY0Vv43v6oFdy5Op/vqm1V1cPvcU15qIUkruSt1jbw=,Piccolo borgo appollaiato tra i monti lucani.\...,2021-12-04 10:39:16 +00:00,5.0,138.0,21.0,True,None,4,"[0.11633721739053726, -0.0018988546216860414, ..."
4,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LG9mZbib8Vqjybu4atSTctvyXtU9rDiKSO3eX0IaX1w=,"Bel paese, ora con il ponte tibetano potrebbe ...",2021-12-04 10:39:16 +00:00,4.0,60.0,17.0,False,None,5,"[-0.1472267359495163, -0.14695429801940918, 0...."

In [8]:
df["unique_id"] = df["unique_id"].apply(lambda x: x - 1)
df.to_parquet(os.path.join(nodes_dir, "review.parquet"))
# df.shape (1700367, 14)
df.head()

,cid,place_id,location_code,type,datetime,profile_url,review_text,timestamp,rating_value,reviews_count,photos_count,local_guide,review_highlights,unique_id,review_text_embedding
0,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,QA1VvS65a3xuYX49qQU2BS1hwqjKID2+kqPadWT8oL8=,Paese di montagna con boschi di faggi e castag...,2020-12-04 10:39:16 +00:00,4.0,100.0,274.0,True,None,0,"[-0.02132909931242466, 0.0855952724814415, 0.0..."
1,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LTZBZHp0ee1g8sWcfwl9CZRctKfoLkNRbtGlbZCDe08=,"Paese caratteristico con tanto da visitare,il ...",2021-12-04 10:39:16 +00:00,5.0,11.0,115.0,True,None,1,"[0.11749532073736191, 0.027359535917639732, 0...."
2,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,Tn9Bq3/3GlLrDgcsZ7AgQk9X9oYPR6pSBzYZpiIjm7E=,Concerto Gospel del 23/12/2021\nOrganizzato da...,2022-12-04 10:39:16 +00:00,5.0,18.0,33.0,True,None,2,"[-0.0026724785566329956, 0.1681678593158722, 0..."
3,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,5gY0Vv43v6oFdy5Op/vqm1V1cPvcU15qIUkruSt1jbw=,Piccolo borgo appollaiato tra i monti lucani.\...,2021-12-04 10:39:16 +00:00,5.0,138.0,21.0,True,None,3,"[0.11633721739053726, -0.0018988546216860414, ..."
4,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LG9mZbib8Vqjybu4atSTctvyXtU9rDiKSO3eX0IaX1w=,"Bel paese, ora con il ponte tibetano potrebbe ...",2021-12-04 10:39:16 +00:00,4.0,60.0,17.0,False,None,4,"[-0.1472267359495163, -0.14695429801940918, 0...."

In [62]:
df = pd.read_parquet(os.path.join(dir_in, f"user_{region_str}.parquet")) 
df.head()

,profile_url,llm_profile_ground_truth,unique_id
0,2c1O2yvNEZrGN/CGBsU5kLYRHnuKgSCSB0DukW8tZqw=,None,1
1,n6SAtWl9vWDPKff9IPpPM1Q3ZkGfWAF7tDqJ7HSMiaQ=,None,2
2,/Xv9eiUDubhp2WiWM4qNHaez18/Czj8oJBgqbHVnbIM=,None,3
3,80mfOhHRT0Mg8NIxhGZjo9qaQUhmsvs7qbKmxoBEx8w=,None,4
4,aBuImX/q5b4lWDVZJsA1rMYFawmf4wk8IUWkAh6oK6Q=,None,5

In [63]:
df["unique_id"] = df["unique_id"].apply(lambda x: x - 1)
df.to_parquet(os.path.join(nodes_dir, "user.parquet"))
#df.shape (590919, 3)
df.head()

,profile_url,llm_profile_ground_truth,unique_id
0,2c1O2yvNEZrGN/CGBsU5kLYRHnuKgSCSB0DukW8tZqw=,None,0
1,n6SAtWl9vWDPKff9IPpPM1Q3ZkGfWAF7tDqJ7HSMiaQ=,None,1
2,/Xv9eiUDubhp2WiWM4qNHaez18/Czj8oJBgqbHVnbIM=,None,2
3,80mfOhHRT0Mg8NIxhGZjo9qaQUhmsvs7qbKmxoBEx8w=,None,3
4,aBuImX/q5b4lWDVZJsA1rMYFawmf4wk8IUWkAh6oK6Q=,None,4

In [64]:
df = pd.read_parquet(os.path.join(dir_in, f"zone_{region_str}.parquet")) 
df.head()

   unique_id     zone
0          1  9053426
1          2  9053429

In [65]:
df["unique_id"] = df["unique_id"].apply(lambda x: x - 1)
df.to_parquet(os.path.join(nodes_dir, "zone.parquet"))
#df.shape (1,2)
df.head()

   unique_id     zone
0          0  9053426
1          1  9053429

EDGES

In [66]:
df = pd.read_parquet(os.path.join(dir_in, f"poi_is_in_zone_{region_str}.parquet")) 
df.head()

   unique_id_poi  unique_id_zone
0           60.0               2
1           60.0               2
2           60.0               2
3           60.0               2
4           60.0               2

In [67]:
uid_columns = [col for col in df.columns if col.startswith('unique_id')]
df_cleaned = df.dropna(subset=uid_columns).copy()
df_cleaned.drop_duplicates(inplace=True)
for col in uid_columns:
    df_cleaned[col] = df_cleaned[col].apply(lambda x: int(x) - 1)
df_cleaned.to_parquet(os.path.join(edges_dir, "poi_is_in_zone.parquet"))
df_cleaned.head()

    unique_id_poi  unique_id_zone
0              59               1
5            4498               1
22           4493               1
26           6230               1
36           4529               1

In [68]:
df = pd.read_parquet(os.path.join(dir_in, f"poi_is_of_category_{region_str}.parquet")) 
df.head()

   unique_id_poi  unique_id_category
0              1              2037.0
1              2                44.0
2              3              2037.0
3              3               883.0
4              4              2037.0

In [69]:
uid_columns = [col for col in df.columns if col.startswith('unique_id')]
df_cleaned = df.dropna(subset=uid_columns).copy()
df_cleaned.drop_duplicates(inplace=True)
for col in uid_columns:
    df_cleaned[col] = df_cleaned[col].apply(lambda x: int(x) - 1)
df_cleaned.to_parquet(os.path.join(edges_dir, "poi_is_of_category.parquet"))
df_cleaned.head()

   unique_id_poi  unique_id_category
0              0                2036
1              1                  43
2              2                2036
3              2                 882
4              3                2036

In [70]:
df = pd.read_parquet(os.path.join(dir_in, f"review_is_about_poi_{region_str}.parquet")) 
df.head()

   unique_id_review  unique_id_poi
0                 1           60.0
1                 2           60.0
2                 3           60.0
3                 4           60.0
4                 5           60.0

In [71]:
uid_columns = [col for col in df.columns if col.startswith('unique_id')]
df_cleaned = df.dropna(subset=uid_columns).copy()
df_cleaned.drop_duplicates(inplace=True)
for col in uid_columns:
    df_cleaned[col] = df_cleaned[col].apply(lambda x: int(x) - 1)
df_cleaned.to_parquet(os.path.join(edges_dir, "review_is_about_poi.parquet"))
df_cleaned.head()

   unique_id_review  unique_id_poi
0                 0             59
1                 1             59
2                 2             59
3                 3             59
4                 4             59

In [72]:
df = pd.read_parquet(os.path.join(dir_in, f"user_visited_poi_{region_str}.parquet")) 
df.head()

   unique_id_poi  unique_id_user
0           60.0          315595
1           60.0          347653
2           60.0          153876
3           60.0          180362
4           60.0          687777

In [73]:
uid_columns = [col for col in df.columns if col.startswith('unique_id')]
df_cleaned = df.dropna(subset=uid_columns)[["unique_id_user", "unique_id_poi"]].copy()
df_cleaned.drop_duplicates(inplace=True)
for col in uid_columns:
    df_cleaned[col] = df_cleaned[col].apply(lambda x: int(x) - 1)
df_cleaned.to_parquet(os.path.join(edges_dir, "user_visited_poi.parquet"))
df_cleaned.head()

   unique_id_user  unique_id_poi
0          315594             59
1          347652             59
2          153875             59
3          180361             59
4          687776             59

In [74]:
df = pd.read_parquet(os.path.join(dir_in, f"user_wrote_review_{region_str}.parquet")) 
df.head()

   unique_id_review  unique_id_user
0                 1          315595
1                 2          347653
2                 3          153876
3                 4          180362
4                 5          687777

In [75]:
uid_columns = [col for col in df.columns if col.startswith('unique_id')]
df_cleaned = df.dropna(subset=uid_columns)[["unique_id_user", "unique_id_review"]].copy()
df_cleaned.drop_duplicates(inplace=True)
for col in uid_columns:
    df_cleaned[col] = df_cleaned[col].apply(lambda x: int(x) - 1)
df_cleaned.to_parquet(os.path.join(edges_dir, "user_wrote_review.parquet"))
df_cleaned.head()

   unique_id_user  unique_id_review
0          315594                 0
1          347652                 1
2          153875                 2
3          180361                 3
4          687776                 4

In [4]:
df_gt = pd.read_parquet(os.path.join(base_dir, "raw_data", "reviews_output_llm_emilia_romagna_50_rev_days.parquet"))
df_gt.head()

,place_id,unique_id_poi,unique_id_review,timestamp,llm_output,llm_explanation,llm_explanation_embedding
0,ChIJ-yzgxuzGLBMRSp616rQ6wcs,1751.0,1987323,2004-02-14 09:35:41+00:00,"{'Curioso': 0.0, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia comfort e servizi come...,"[0.20401997864246368, -0.002712620422244072, -..."
1,ChIJG6U3lWndLBMRucpnijC1vbo,8998.0,2195409,2004-02-14 10:14:17+00:00,"{'Curioso': 0.0, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia unesperienza piacevole...,"[0.07756330072879791, -0.005198420025408268, -..."
2,ChIJp4978hLDLBMRN9PUr6Ax1ok,258.0,2099614,2005-02-14 10:14:39+00:00,"{'Curioso': 0.0, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia aspetti di comfort e p...,"[0.21484680473804474, 0.04393579810857773, 0.0..."
3,ChIJN4M7dBTDLBMRrFXsYPsUUQw,4601.0,2155920,2005-02-14 10:14:19+00:00,"{'Curioso': 0.2, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia un viaggio di coppia i...,"[0.06440079212188721, 0.23389777541160583, -0...."
4,ChIJD5_u9LDsLBMRvHAKst5I4Wg,4196.0,2132576,2006-02-14 10:11:32+00:00,"{'Curioso': 0.1, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia un soggiorno di una no...,"[0.13304750621318817, 0.019133800640702248, -0..."

In [5]:
df_gt["unique_id_review"] = df_gt["unique_id_review"].apply(lambda x: x - 1)
df_gt.drop(["unique_id_poi"], axis=1, inplace=True)
df_gt.to_parquet(os.path.join(nodes_dir, "reviews_output_llm_50_rev_days.parquet"), index= False)
df_gt.head()

,place_id,unique_id_review,timestamp,llm_output,llm_explanation,llm_explanation_embedding
0,ChIJ-yzgxuzGLBMRSp616rQ6wcs,1987322,2004-02-14 09:35:41+00:00,"{'Curioso': 0.0, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia comfort e servizi come...,"[0.20401997864246368, -0.002712620422244072, -..."
1,ChIJG6U3lWndLBMRucpnijC1vbo,2195408,2004-02-14 10:14:17+00:00,"{'Curioso': 0.0, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia unesperienza piacevole...,"[0.07756330072879791, -0.005198420025408268, -..."
2,ChIJp4978hLDLBMRN9PUr6Ax1ok,2099613,2005-02-14 10:14:39+00:00,"{'Curioso': 0.0, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia aspetti di comfort e p...,"[0.21484680473804474, 0.04393579810857773, 0.0..."
3,ChIJN4M7dBTDLBMRrFXsYPsUUQw,2155919,2005-02-14 10:14:19+00:00,"{'Curioso': 0.2, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia un viaggio di coppia i...,"[0.06440079212188721, 0.23389777541160583, -0...."
4,ChIJD5_u9LDsLBMRvHAKst5I4Wg,2132575,2006-02-14 10:11:32+00:00,"{'Curioso': 0.1, 'Esploratore': 0.0, 'Colto': ...",La recensione evidenzia un soggiorno di una no...,"[0.13304750621318817, 0.019133800640702248, -0..."