In [1]:
import os
import pandas as pd
import numpy as np

from src.utils import get_base_dir, load_from_pickle

In [2]:
dataset = "dooway"
region = "Basilicata" # "EmiliaRomagna"
region_str = region.lower() # "emilia_romagna"
base_dir = os.path.join(get_base_dir(), region)
subset_dir = os.path.join(base_dir, "subset")
nodes_dir = os.path.join(subset_dir, "heterodata", "features", "dataframes")
edges_dir = os.path.join(subset_dir, "heterodata", "edgelists", "dataframes")

In [14]:
df_R = pd.read_parquet(os.path.join(nodes_dir, "review.parquet")) #unique_id, review_text_embedding
df_R.head()

,timestamp,rating_value,local_guide,unique_id,review_text_embedding,positive_quality,negative_quality,noise_level,group_size,waiting_time,description_embedding
0,2020-12-04 10:39:16+00:00,4.0,True,0,"[-0.02132909931242466, 0.0855952724814415, 0.0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
1,2021-12-04 10:39:16+00:00,5.0,True,1,"[0.11749532073736191, 0.027359535917639732, 0....",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
2,2022-12-04 10:39:16+00:00,5.0,True,2,"[-0.0026724785566329956, 0.1681678593158722, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
3,2021-12-04 10:39:16+00:00,5.0,True,3,"[0.11633721739053726, -0.0018988546216860414, ...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
4,2021-12-04 10:39:16+00:00,4.0,False,4,"[-0.1472267359495163, -0.14695429801940918, 0....",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."

In [15]:
df_R.tail()

,timestamp,rating_value,local_guide,unique_id,review_text_embedding,positive_quality,negative_quality,noise_level,group_size,waiting_time,description_embedding
1597210,2024-01-13 10:29:33+00:00,5.0,False,1597210,"[0.12187313990745491, -0.024273028586362592, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
1597211,2024-01-13 10:29:33+00:00,5.0,True,1597211,"[0.12187313990745491, -0.024273028586362592, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
1597212,2024-01-13 10:29:33+00:00,5.0,False,1597212,"[0.12187313990745491, -0.024273028586362592, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
1597213,2024-01-13 10:29:33+00:00,5.0,False,1597213,"[0.12187313990745491, -0.024273028586362592, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."
1597214,2024-01-13 10:29:33+00:00,5.0,False,1597214,"[0.12187313990745491, -0.024273028586362592, 0...",False,False,-1,-1,-1,"[0.0973015590350905, 0.048725716206544194, 0.0..."

In [3]:
df_UR= pd.read_parquet(os.path.join(edges_dir, "user_wrote_review.parquet")) #unique_id_user, unique_id_review
df_UR.head()

   unique_id_user  unique_id_review
0            1094                 0
1            3508                 1
2            2174                 2
3            2743                 3
4            2812                 4

In [4]:
k=8
df_gt = pd.read_parquet(os.path.join(subset_dir, f"users_avg_multilabel_k{k}.parquet"))
df_gt.head()

,unique_id_user,animal_lover,beach_person,cultured,curious,disorganized,explorer,family_oriented,genZ,digital_nomad,lazy,romantic,free_spirit,business_traveler,online_traveler,eco_traveler
0,0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
3,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
4,4,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0

In [7]:
df_gt.shape

(3543, 16)

In [8]:
df_R_ok = df_R[['unique_id', 'review_text_embedding']]

df_result = df_UR.merge(
    df_R_ok,
    left_on='unique_id_review',
    right_on='unique_id',
    how='left'
)

df_result = df_result.drop(columns=['unique_id'])
df_result = df_result[['unique_id_user', 'review_text_embedding']]
#df_result.to_parquet(os.path.join(subset_dir, "competitors", "user_reviews_embs.parquet"), index=False)
df_result.head()

   unique_id_user                              review_text_embedding
0            1094  [-0.02132909931242466, 0.0855952724814415, 0.0...
1            3508  [0.11749532073736191, 0.027359535917639732, 0....
2            2174  [-0.0026724785566329956, 0.1681678593158722, 0...
3            2743  [0.11633721739053726, -0.0018988546216860414, ...
4            2812  [-0.1472267359495163, -0.14695429801940918, 0....

In [10]:
df_user_embeddings = (
    df_result
    .groupby("unique_id_user")["review_text_embedding"]
    .apply(lambda embeddings: np.mean(np.vstack(embeddings), axis=0))
    .reset_index()
)

df_user_embeddings.head()

   unique_id_user                              review_text_embedding
0               0  [0.04751778452211207, -0.048406967570648954, 0...
1               1  [0.09193745344938477, -0.0619653747451353, 0.0...
2               2  [0.13446582286902095, 0.0012383818342957807, -...
3               3  [0.15386784076690674, 0.31292763352394104, 0.1...
4               4  [0.15968314585405435, -0.06351978766059041, 0....

In [11]:
df_user_embeddings.shape

(3540, 2)

In [12]:
df_user_embeddings["unique_id_user"].max()

3542

In [15]:
# 1. Compute the global mean embedding across all users that have embeddings
global_mean_embedding = np.mean(
    np.vstack(df_user_embeddings["review_text_embedding"].values),
    axis=0
)

# 2. Merge keeping all rows from df_gt
df_final = df_gt.merge(df_user_embeddings, on="unique_id_user", how="left")

# 3. Fill missing embeddings with the global mean
df_final["review_text_embedding"] = df_final["review_text_embedding"].apply(
    lambda x: global_mean_embedding if isinstance(x, float) and np.isnan(x) else x
)

df_final.to_parquet(os.path.join(subset_dir, "competitors", "user_reviews_embs.parquet"), index=False)
df_final.head()

,unique_id_user,animal_lover,beach_person,cultured,curious,disorganized,explorer,family_oriented,genZ,digital_nomad,lazy,romantic,free_spirit,business_traveler,online_traveler,eco_traveler,review_text_embedding
0,0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,"[0.04751778452211207, -0.048406967570648954, 0..."
1,1,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,"[0.09193745344938477, -0.0619653747451353, 0.0..."
2,2,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,"[0.13446582286902095, 0.0012383818342957807, -..."
3,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,"[0.15386784076690674, 0.31292763352394104, 0.1..."
4,4,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,"[0.15968314585405435, -0.06351978766059041, 0...."

In [17]:
df_final.shape

(3543, 17)

In [3]:
seed = 42

df = pd.read_parquet(os.path.join(subset_dir, f"split_flags_{seed}.parquet"))
df.head()

   id_utente  train  validation   test
0          0   True       False  False
1          1   True       False  False
2          2   True       False  False
3          3   True       False  False
4          4   True       False  False

In [5]:
df_review = pd.read_parquet(os.path.join(base_dir, "original_data", "nodes", "review.parquet")) 
df_review.head()

,cid,place_id,location_code,type,datetime,profile_url,review_text,timestamp,rating_value,reviews_count,photos_count,local_guide,review_highlights,unique_id,review_text_embedding
0,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,QA1VvS65a3xuYX49qQU2BS1hwqjKID2+kqPadWT8oL8=,Paese di montagna con boschi di faggi e castag...,2020-12-04 10:39:16 +00:00,4.0,100.0,274.0,True,None,0,"[-0.02132909931242466, 0.0855952724814415, 0.0..."
1,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LTZBZHp0ee1g8sWcfwl9CZRctKfoLkNRbtGlbZCDe08=,"Paese caratteristico con tanto da visitare,il ...",2021-12-04 10:39:16 +00:00,5.0,11.0,115.0,True,None,1,"[0.11749532073736191, 0.027359535917639732, 0...."
2,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,Tn9Bq3/3GlLrDgcsZ7AgQk9X9oYPR6pSBzYZpiIjm7E=,Concerto Gospel del 23/12/2021\nOrganizzato da...,2022-12-04 10:39:16 +00:00,5.0,18.0,33.0,True,None,2,"[-0.0026724785566329956, 0.1681678593158722, 0..."
3,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,5gY0Vv43v6oFdy5Op/vqm1V1cPvcU15qIUkruSt1jbw=,Piccolo borgo appollaiato tra i monti lucani.\...,2021-12-04 10:39:16 +00:00,5.0,138.0,21.0,True,None,3,"[0.11633721739053726, -0.0018988546216860414, ..."
4,6526278041137503800,ChIJdeNxK7UyPxMRON5u-0z_kVo,9053426,google_reviews,2023-12-04 10:39:53 +00:00,LG9mZbib8Vqjybu4atSTctvyXtU9rDiKSO3eX0IaX1w=,"Bel paese, ora con il ponte tibetano potrebbe ...",2021-12-04 10:39:16 +00:00,4.0,60.0,17.0,False,None,4,"[-0.1472267359495163, -0.14695429801940918, 0...."

In [11]:
df_review.tail()

,cid,place_id,location_code,type,datetime,profile_url,review_text,timestamp,rating_value,reviews_count,photos_count,local_guide,review_highlights,unique_id,review_text_embedding
1700362,13288306697958816570,ChIJDe0b9bR_RxMROntHjomMabg,9053426,google_reviews,2025-01-13 10:29:37 +00:00,pU6EeQLTz4LseY3B31+ugyLpF4FTQeGzRv7keXpS7Xs=,None,2024-01-13 10:29:33 +00:00,5.0,NaN,NaN,False,None,1700362,None
1700363,13288306697958816570,ChIJDe0b9bR_RxMROntHjomMabg,9053426,google_reviews,2025-01-13 10:29:37 +00:00,qSIgINeaBBAKJtAglo1RHGj1jxJumobmFN1ffvEvmgo=,None,2024-01-13 10:29:33 +00:00,5.0,35.0,22.0,True,None,1700363,None
1700364,13288306697958816570,ChIJDe0b9bR_RxMROntHjomMabg,9053426,google_reviews,2025-01-13 10:29:37 +00:00,jz+qgu4eUORheVlMwQxPDmIsRYnuaIgbLb6Tyd8yIDI=,None,2024-01-13 10:29:33 +00:00,5.0,NaN,NaN,False,None,1700364,None
1700365,13288306697958816570,ChIJDe0b9bR_RxMROntHjomMabg,9053426,google_reviews,2025-01-13 10:29:37 +00:00,xxQKYrPWq9iSXVe+NzqTUL8wRu5atgThKmBFWt7++Wo=,None,2024-01-13 10:29:33 +00:00,5.0,NaN,NaN,False,None,1700365,None
1700366,13288306697958816570,ChIJDe0b9bR_RxMROntHjomMabg,9053426,google_reviews,2025-01-13 10:29:37 +00:00,8w+I2cWxoJ1xxuj6tLixqghXgU2pARdcTV1irqeo03k=,None,2024-01-13 10:29:33 +00:00,5.0,4.0,NaN,False,None,1700366,None

In [6]:
mapping_R = load_from_pickle(os.path.join(subset_dir, "mapping.pkl"))["review"] #new --> old
mapping_R

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 22,
 23: 23,
 24: 24,
 25: 25,
 26: 26,
 27: 27,
 28: 28,
 29: 29,
 30: 30,
 31: 31,
 32: 32,
 33: 33,
 34: 34,
 35: 35,
 36: 36,
 37: 37,
 38: 38,
 39: 39,
 40: 40,
 41: 41,
 42: 42,
 43: 43,
 44: 44,
 45: 45,
 46: 46,
 47: 47,
 48: 48,
 49: 49,
 50: 50,
 51: 51,
 52: 52,
 53: 53,
 54: 54,
 55: 55,
 56: 56,
 57: 57,
 58: 58,
 59: 59,
 60: 75,
 61: 76,
 62: 77,
 63: 78,
 64: 79,
 65: 80,
 66: 81,
 67: 82,
 68: 83,
 69: 84,
 70: 85,
 71: 86,
 72: 87,
 73: 88,
 74: 89,
 75: 90,
 76: 91,
 77: 92,
 78: 93,
 79: 94,
 80: 95,
 81: 96,
 82: 97,
 83: 98,
 84: 99,
 85: 100,
 86: 101,
 87: 102,
 88: 103,
 89: 104,
 90: 105,
 91: 106,
 92: 107,
 93: 108,
 94: 109,
 95: 110,
 96: 111,
 97: 112,
 98: 113,
 99: 114,
 100: 115,
 101: 116,
 102: 117,
 103: 118,
 104: 119,
 105: 120,
 106: 121,
 107: 122,
 108: 123,
 109: 124,
 110: 125,
 111: 126,
 112: 127,
 113: 128,
 114: 129,
 115: 130,
 116: 131,
 117: 132,
 118: 134,
 119: 135,
 120: 136,
 121: 137,
 122: 138,
 123: 139,
 124: 140,
 125: 141,
 126: 142,
 127: 143,
 128: 144,
 129: 145,
 130: 146,
 131: 147,
 132: 148,
 133: 149,
 134: 150,
 135: 151,
 136: 152,
 137: 153,
 138: 154,
 139: 155,
 140: 156,
 141: 157,
 142: 158,
 143: 159,
 144: 160,
 145: 161,
 146: 162,
 147: 163,
 148: 164,
 149: 165,
 150: 166,
 151: 167,
 152: 168,
 153: 169,
 154: 170,
 155: 171,
 156: 172,
 157: 173,
 158: 174,
 159: 175,
 160: 176,
 161: 177,
 162: 178,
 163: 179,
 164: 180,
 165: 181,
 166: 182,
 167: 183,
 168: 184,
 169: 185,
 170: 186,
 171: 187,
 172: 188,
 173: 189,
 174: 190,
 175: 191,
 176: 192,
 177: 193,
 178: 194,
 179: 195,
 180: 196,
 181: 197,
 182: 198,
 183: 199,
 184: 200,
 185: 201,
 186: 202,
 187: 203,
 188: 204,
 189: 205,
 190: 206,
 191: 207,
 192: 208,
 193: 209,
 194: 210,
 195: 211,
 196: 212,
 197: 213,
 198: 214,
 199: 215,
 200: 216,
 201: 217,
 202: 218,
 203: 219,
 204: 220,
 205: 221,
 206: 222,
 207: 223,
 208: 224,
 209: 225,
 210: 226,
 211: 227,
 212: 228,
 213: 229,
 214: 230,
 215: 231,
 216: 232,
 217: 233,
 218: 234,
 219: 235,
 220: 236,
 221: 237,
 222: 238,
 223: 239,
 224: 240,
 225: 241,
 226: 242,
 227: 243,
 228: 244,
 229: 245,
 230: 246,
 231: 247,
 232: 248,
 233: 249,
 234: 250,
 235: 251,
 236: 252,
 237: 253,
 238: 254,
 239: 255,
 240: 256,
 241: 257,
 242: 258,
 243: 259,
 244: 260,
 245: 261,
 246: 262,
 247: 263,
 248: 264,
 249: 265,
 250: 266,
 251: 267,
 252: 268,
 253: 269,
 254: 270,
 255: 271,
 256: 272,
 257: 273,
 258: 274,
 259: 275,
 260: 276,
 261: 277,
 262: 278,
 263: 279,
 264: 280,
 265: 281,
 266: 282,
 267: 283,
 268: 284,
 269: 285,
 270: 286,
 271: 287,
 272: 288,
 273: 289,
 274: 290,
 275: 291,
 276: 292,
 277: 293,
 278: 294,
 279: 295,
 280: 296,
 281: 297,
 282: 298,
 283: 299,
 284: 300,
 285: 301,
 286: 302,
 287: 303,
 288: 304,
 289: 305,
 290: 306,
 291: 307,
 292: 308,
 293: 309,
 294: 310,
 295: 311,
 296: 312,
 297: 313,
 298: 314,
 299: 315,
 300: 316,
 301: 317,
 302: 318,
 303: 319,
 304: 320,
 305: 321,
 306: 322,
 307: 323,
 308: 324,
 309: 325,
 310: 326,
 311: 327,
 312: 328,
 313: 329,
 314: 330,
 315: 331,
 316: 332,
 317: 333,
 318: 334,
 319: 335,
 320: 336,
 321: 337,
 322: 338,
 323: 339,
 324: 340,
 325: 341,
 326: 342,
 327: 343,
 328: 344,
 329: 345,
 330: 346,
 331: 347,
 332: 348,
 333: 349,
 334: 350,
 335: 351,
 336: 352,
 337: 353,
 338: 354,
 339: 355,
 340: 356,
 341: 357,
 342: 358,
 343: 359,
 344: 360,
 345: 361,
 346: 362,
 347: 363,
 348: 364,
 349: 365,
 350: 366,
 351: 367,
 352: 368,
 353: 369,
 354: 370,
 355: 371,
 356: 372,
 357: 373,
 358: 374,
 359: 375,
 360: 376,
 361: 377,
 362: 378,
 363: 379,
 364: 380,
 365: 381,
 366: 382,
 367: 383,
 368: 384,
 369: 385,
 370: 386,
 371: 387,
 372: 388,
 373: 389,
 374: 390,
 375: 391,
 376: 392,
 377: 393,
 378: 394,
 379: 395,
 380: 396,
 381: 397,
 382: 398,
 383: 399,
 384: 400,
 385: 401,
 386: 402,
 387: 403,
 388: 404,
 389: 405,
 390: 406,
 391: 407,
 392: 408,
 393: 409,
 394: 410,
 395: 411,
 396: 412,
 397: 413,
 398: 414,
 399: 415,
 400: 416,
 401: 417,
 402: 418,
 403: 419,
 404: 420,
 405: 421,
 406: 422,
 407: 423,
 408: 424,
 409: 425,
 410: 426,
 411: 427,
 412: 428,
 413: 429,
 414: 430,
 415: 431,
 416: 432,
 417: 433,
 418: 434,
 419: 435,
 420: 436,
 421: 437,
 422: 438,
 423: 439,
 424: 440,
 425: 441,
 426: 442,
 427: 443,
 428: 444,
 429: 445,
 430: 446,
 431: 447,
 432: 448,
 433: 449,
 434: 450,
 435: 451,
 436: 452,
 437: 453,
 438: 454,
 439: 455,
 440: 456,
 441: 457,
 442: 458,
 443: 459,
 444: 460,
 445: 461,
 446: 462,
 447: 463,
 448: 464,
 449: 465,
 450: 466,
 451: 467,
 452: 468,
 453: 469,
 454: 470,
 455: 471,
 456: 472,
 457: 473,
 458: 474,
 459: 475,
 460: 476,
 461: 477,
 462: 478,
 463: 479,
 464: 480,
 465: 481,
 466: 482,
 467: 483,
 468: 484,
 469: 485,
 470: 486,
 471: 487,
 472: 488,
 473: 489,
 474: 490,
 475: 491,
 476: 492,
 477: 493,
 478: 494,
 479: 495,
 480: 496,
 481: 497,
 482: 498,
 483: 499,
 484: 500,
 485: 501,
 486: 502,
 487: 504,
 488: 505,
 489: 506,
 490: 515,
 491: 516,
 492: 517,
 493: 518,
 494: 519,
 495: 520,
 496: 521,
 497: 522,
 498: 523,
 499: 524,
 500: 525,
 501: 526,
 502: 527,
 503: 528,
 504: 529,
 505: 530,
 506: 533,
 507: 534,
 508: 540,
 509: 541,
 510: 542,
 511: 543,
 512: 544,
 513: 545,
 514: 546,
 515: 547,
 516: 548,
 517: 549,
 518: 550,
 519: 551,
 520: 552,
 521: 553,
 522: 554,
 523: 555,
 524: 556,
 525: 557,
 526: 558,
 527: 559,
 528: 560,
 529: 561,
 530: 562,
 531: 563,
 532: 564,
 533: 565,
 534: 566,
 535: 567,
 536: 568,
 537: 569,
 538: 570,
 539: 571,
 540: 572,
 541: 573,
 542: 574,
 543: 575,
 544: 576,
 545: 577,
 546: 578,
 547: 579,
 548: 580,
 549: 581,
 550: 582,
 551: 583,
 552: 584,
 553: 585,
 554: 586,
 555: 587,
 556: 588,
 557: 589,
 558: 590,
 559: 591,
 560: 592,
 561: 593,
 562: 594,
 563: 595,
 564: 596,
 565: 597,
 566: 598,
 567: 599,
 568: 600,
 569: 601,
 570: 602,
 571: 603,
 572: 604,
 573: 605,
 574: 606,
 575: 607,
 576: 608,
 577: 609,
 578: 610,
 579: 611,
 580: 612,
 581: 613,
 582: 614,
 583: 615,
 584: 616,
 585: 617,
 586: 618,
 587: 619,
 588: 620,
 589: 621,
 590: 622,
 591: 623,
 592: 624,
 593: 625,
 594: 626,
 595: 627,
 596: 628,
 597: 629,
 598: 630,
 599: 631,
 600: 632,
 601: 633,
 602: 634,
 603: 635,
 604: 636,
 605: 637,
 606: 638,
 607: 639,
 608: 640,
 609: 641,
 610: 642,
 611: 643,
 612: 644,
 613: 645,
 614: 646,
 615: 647,
 616: 648,
 617: 649,
 618: 650,
 619: 651,
 620: 652,
 621: 653,
 622: 654,
 623: 655,
 624: 656,
 625: 657,
 626: 658,
 627: 659,
 628: 660,
 629: 661,
 630: 662,
 631: 663,
 632: 664,
 633: 665,
 634: 666,
 635: 667,
 636: 668,
 637: 669,
 638: 670,
 639: 671,
 640: 672,
 641: 673,
 642: 674,
 643: 675,
 644: 676,
 645: 677,
 646: 678,
 647: 679,
 648: 680,
 649: 681,
 650: 682,
 651: 683,
 652: 684,
 653: 685,
 654: 686,
 655: 687,
 656: 688,
 657: 689,
 658: 690,
 659: 691,
 660: 692,
 661: 693,
 662: 694,
 663: 695,
 664: 696,
 665: 697,
 666: 698,
 667: 699,
 668: 700,
 669: 701,
 670: 702,
 671: 703,
 672: 704,
 673: 705,
 674: 706,
 675: 707,
 676: 708,
 677: 709,
 678: 710,
 679: 711,
 680: 712,
 681: 713,
 682: 714,
 683: 715,
 684: 716,
 685: 717,
 686: 718,
 687: 719,
 688: 720,
 689: 721,
 690: 722,
 691: 723,
 692: 724,
 693: 725,
 694: 726,
 695: 727,
 696: 728,
 697: 729,
 698: 730,
 699: 731,
 700: 732,
 701: 733,
 702: 734,
 703: 735,
 704: 736,
 705: 737,
 706: 738,
 707: 739,
 708: 740,
 709: 741,
 710: 742,
 711: 743,
 712: 744,
 713: 745,
 714: 746,
 715: 747,
 716: 748,
 717: 749,
 718: 750,
 719: 751,
 720: 752,
 721: 753,
 722: 754,
 723: 755,
 724: 756,
 725: 757,
 726: 758,
 727: 759,
 728: 760,
 729: 761,
 730: 762,
 731: 763,
 732: 764,
 733: 765,
 734: 766,
 735: 767,
 736: 768,
 737: 769,
 738: 770,
 739: 771,
 740: 772,
 741: 773,
 742: 774,
 743: 775,
 744: 776,
 745: 777,
 746: 778,
 747: 779,
 748: 780,
 749: 781,
 750: 782,
 751: 783,
 752: 784,
 753: 785,
 754: 786,
 755: 787,
 756: 788,
 757: 789,
 758: 790,
 759: 791,
 760: 792,
 761: 793,
 762: 794,
 763: 795,
 764: 796,
 765: 797,
 766: 798,
 767: 799,
 768: 800,
 769: 801,
 770: 802,
 771: 803,
 772: 804,
 773: 805,
 774: 806,
 775: 807,
 776: 808,
 777: 809,
 778: 810,
 779: 811,
 780: 812,
 781: 813,
 782: 814,
 783: 815,
 784: 816,
 785: 817,
 786: 818,
 787: 819,
 788: 820,
 789: 821,
 790: 822,
 791: 823,
 792: 824,
 793: 825,
 794: 826,
 795: 827,
 796: 828,
 797: 829,
 798: 830,
 799: 831,
 800: 832,
 801: 833,
 802: 834,
 803: 835,
 804: 836,
 805: 837,
 806: 838,
 807: 839,
 808: 840,
 809: 841,
 810: 842,
 811: 843,
 812: 844,
 813: 845,
 814: 846,
 815: 847,
 816: 848,
 817: 849,
 818: 850,
 819: 851,
 820: 852,
 821: 853,
 822: 854,
 823: 855,
 824: 856,
 825: 857,
 826: 858,
 827: 859,
 828: 860,
 829: 861,
 830: 862,
 831: 863,
 832: 864,
 833: 865,
 834: 866,
 835: 867,
 836: 868,
 837: 869,
 838: 870,
 839: 871,
 840: 872,
 841: 873,
 842: 874,
 843: 875,
 844: 876,
 845: 877,
 846: 878,
 847: 879,
 848: 880,
 849: 881,
 850: 882,
 851: 883,
 852: 884,
 853: 885,
 854: 886,
 855: 887,
 856: 888,
 857: 889,
 858: 890,
 859: 891,
 860: 892,
 861: 893,
 862: 894,
 863: 895,
 864: 896,
 865: 897,
 866: 898,
 867: 899,
 868: 900,
 869: 901,
 870: 902,
 871: 903,
 872: 904,
 873: 905,
 874: 906,
 875: 907,
 876: 908,
 877: 909,
 878: 910,
 879: 911,
 880: 912,
 881: 913,
 882: 914,
 883: 915,
 884: 916,
 885: 917,
 886: 918,
 887: 919,
 888: 920,
 889: 921,
 890: 922,
 891: 923,
 892: 924,
 893: 925,
 894: 926,
 895: 927,
 896: 928,
 897: 929,
 898: 930,
 899: 931,
 900: 932,
 901: 933,
 902: 934,
 903: 935,
 904: 936,
 905: 937,
 906: 938,
 907: 939,
 908: 940,
 909: 941,
 910: 942,
 911: 943,
 912: 944,
 913: 945,
 914: 946,
 915: 947,
 916: 948,
 917: 949,
 918: 950,
 919: 951,
 920: 952,
 921: 953,
 922: 954,
 923: 955,
 924: 956,
 925: 957,
 926: 958,
 927: 959,
 928: 960,
 929: 961,
 930: 962,
 931: 963,
 932: 964,
 933: 965,
 934: 966,
 935: 967,
 936: 968,
 937: 969,
 938: 970,
 939: 971,
 940: 972,
 941: 973,
 942: 974,
 943: 975,
 944: 976,
 945: 977,
 946: 978,
 947: 979,
 948: 980,
 949: 981,
 950: 982,
 951: 983,
 952: 984,
 953: 985,
 954: 986,
 955: 987,
 956: 988,
 957: 989,
 958: 990,
 959: 991,
 960: 992,
 961: 993,
 962: 994,
 963: 995,
 964: 996,
 965: 997,
 966: 998,
 967: 999,
 968: 1000,
 969: 1001,
 970: 1002,
 971: 1003,
 972: 1004,
 973: 1005,
 974: 1006,
 975: 1007,
 976: 1008,
 977: 1009,
 978: 1010,
 979: 1011,
 980: 1012,
 981: 1013,
 982: 1014,
 983: 1015,
 984: 1016,
 985: 1017,
 986: 1018,
 987: 1019,
 988: 1020,
 989: 1021,
 990: 1022,
 991: 1023,
 992: 1024,
 993: 1025,
 994: 1026,
 995: 1027,
 996: 1028,
 997: 1029,
 998: 1030,
 999: 1031,
 ...}

In [7]:
mapping_R_rev = {v: k for k, v in mapping_R.items()} #old --> new
mapping_R_rev

{0: 0,
 1: 1,
 2: 2,
 3: 3,
 4: 4,
 5: 5,
 6: 6,
 7: 7,
 8: 8,
 9: 9,
 10: 10,
 11: 11,
 12: 12,
 13: 13,
 14: 14,
 15: 15,
 16: 16,
 17: 17,
 18: 18,
 19: 19,
 20: 20,
 21: 21,
 22: 22,
 23: 23,
 24: 24,
 25: 25,
 26: 26,
 27: 27,
 28: 28,
 29: 29,
 30: 30,
 31: 31,
 32: 32,
 33: 33,
 34: 34,
 35: 35,
 36: 36,
 37: 37,
 38: 38,
 39: 39,
 40: 40,
 41: 41,
 42: 42,
 43: 43,
 44: 44,
 45: 45,
 46: 46,
 47: 47,
 48: 48,
 49: 49,
 50: 50,
 51: 51,
 52: 52,
 53: 53,
 54: 54,
 55: 55,
 56: 56,
 57: 57,
 58: 58,
 59: 59,
 75: 60,
 76: 61,
 77: 62,
 78: 63,
 79: 64,
 80: 65,
 81: 66,
 82: 67,
 83: 68,
 84: 69,
 85: 70,
 86: 71,
 87: 72,
 88: 73,
 89: 74,
 90: 75,
 91: 76,
 92: 77,
 93: 78,
 94: 79,
 95: 80,
 96: 81,
 97: 82,
 98: 83,
 99: 84,
 100: 85,
 101: 86,
 102: 87,
 103: 88,
 104: 89,
 105: 90,
 106: 91,
 107: 92,
 108: 93,
 109: 94,
 110: 95,
 111: 96,
 112: 97,
 113: 98,
 114: 99,
 115: 100,
 116: 101,
 117: 102,
 118: 103,
 119: 104,
 120: 105,
 121: 106,
 122: 107,
 123: 108,
 124: 109,
 125: 110,
 126: 111,
 127: 112,
 128: 113,
 129: 114,
 130: 115,
 131: 116,
 132: 117,
 134: 118,
 135: 119,
 136: 120,
 137: 121,
 138: 122,
 139: 123,
 140: 124,
 141: 125,
 142: 126,
 143: 127,
 144: 128,
 145: 129,
 146: 130,
 147: 131,
 148: 132,
 149: 133,
 150: 134,
 151: 135,
 152: 136,
 153: 137,
 154: 138,
 155: 139,
 156: 140,
 157: 141,
 158: 142,
 159: 143,
 160: 144,
 161: 145,
 162: 146,
 163: 147,
 164: 148,
 165: 149,
 166: 150,
 167: 151,
 168: 152,
 169: 153,
 170: 154,
 171: 155,
 172: 156,
 173: 157,
 174: 158,
 175: 159,
 176: 160,
 177: 161,
 178: 162,
 179: 163,
 180: 164,
 181: 165,
 182: 166,
 183: 167,
 184: 168,
 185: 169,
 186: 170,
 187: 171,
 188: 172,
 189: 173,
 190: 174,
 191: 175,
 192: 176,
 193: 177,
 194: 178,
 195: 179,
 196: 180,
 197: 181,
 198: 182,
 199: 183,
 200: 184,
 201: 185,
 202: 186,
 203: 187,
 204: 188,
 205: 189,
 206: 190,
 207: 191,
 208: 192,
 209: 193,
 210: 194,
 211: 195,
 212: 196,
 213: 197,
 214: 198,
 215: 199,
 216: 200,
 217: 201,
 218: 202,
 219: 203,
 220: 204,
 221: 205,
 222: 206,
 223: 207,
 224: 208,
 225: 209,
 226: 210,
 227: 211,
 228: 212,
 229: 213,
 230: 214,
 231: 215,
 232: 216,
 233: 217,
 234: 218,
 235: 219,
 236: 220,
 237: 221,
 238: 222,
 239: 223,
 240: 224,
 241: 225,
 242: 226,
 243: 227,
 244: 228,
 245: 229,
 246: 230,
 247: 231,
 248: 232,
 249: 233,
 250: 234,
 251: 235,
 252: 236,
 253: 237,
 254: 238,
 255: 239,
 256: 240,
 257: 241,
 258: 242,
 259: 243,
 260: 244,
 261: 245,
 262: 246,
 263: 247,
 264: 248,
 265: 249,
 266: 250,
 267: 251,
 268: 252,
 269: 253,
 270: 254,
 271: 255,
 272: 256,
 273: 257,
 274: 258,
 275: 259,
 276: 260,
 277: 261,
 278: 262,
 279: 263,
 280: 264,
 281: 265,
 282: 266,
 283: 267,
 284: 268,
 285: 269,
 286: 270,
 287: 271,
 288: 272,
 289: 273,
 290: 274,
 291: 275,
 292: 276,
 293: 277,
 294: 278,
 295: 279,
 296: 280,
 297: 281,
 298: 282,
 299: 283,
 300: 284,
 301: 285,
 302: 286,
 303: 287,
 304: 288,
 305: 289,
 306: 290,
 307: 291,
 308: 292,
 309: 293,
 310: 294,
 311: 295,
 312: 296,
 313: 297,
 314: 298,
 315: 299,
 316: 300,
 317: 301,
 318: 302,
 319: 303,
 320: 304,
 321: 305,
 322: 306,
 323: 307,
 324: 308,
 325: 309,
 326: 310,
 327: 311,
 328: 312,
 329: 313,
 330: 314,
 331: 315,
 332: 316,
 333: 317,
 334: 318,
 335: 319,
 336: 320,
 337: 321,
 338: 322,
 339: 323,
 340: 324,
 341: 325,
 342: 326,
 343: 327,
 344: 328,
 345: 329,
 346: 330,
 347: 331,
 348: 332,
 349: 333,
 350: 334,
 351: 335,
 352: 336,
 353: 337,
 354: 338,
 355: 339,
 356: 340,
 357: 341,
 358: 342,
 359: 343,
 360: 344,
 361: 345,
 362: 346,
 363: 347,
 364: 348,
 365: 349,
 366: 350,
 367: 351,
 368: 352,
 369: 353,
 370: 354,
 371: 355,
 372: 356,
 373: 357,
 374: 358,
 375: 359,
 376: 360,
 377: 361,
 378: 362,
 379: 363,
 380: 364,
 381: 365,
 382: 366,
 383: 367,
 384: 368,
 385: 369,
 386: 370,
 387: 371,
 388: 372,
 389: 373,
 390: 374,
 391: 375,
 392: 376,
 393: 377,
 394: 378,
 395: 379,
 396: 380,
 397: 381,
 398: 382,
 399: 383,
 400: 384,
 401: 385,
 402: 386,
 403: 387,
 404: 388,
 405: 389,
 406: 390,
 407: 391,
 408: 392,
 409: 393,
 410: 394,
 411: 395,
 412: 396,
 413: 397,
 414: 398,
 415: 399,
 416: 400,
 417: 401,
 418: 402,
 419: 403,
 420: 404,
 421: 405,
 422: 406,
 423: 407,
 424: 408,
 425: 409,
 426: 410,
 427: 411,
 428: 412,
 429: 413,
 430: 414,
 431: 415,
 432: 416,
 433: 417,
 434: 418,
 435: 419,
 436: 420,
 437: 421,
 438: 422,
 439: 423,
 440: 424,
 441: 425,
 442: 426,
 443: 427,
 444: 428,
 445: 429,
 446: 430,
 447: 431,
 448: 432,
 449: 433,
 450: 434,
 451: 435,
 452: 436,
 453: 437,
 454: 438,
 455: 439,
 456: 440,
 457: 441,
 458: 442,
 459: 443,
 460: 444,
 461: 445,
 462: 446,
 463: 447,
 464: 448,
 465: 449,
 466: 450,
 467: 451,
 468: 452,
 469: 453,
 470: 454,
 471: 455,
 472: 456,
 473: 457,
 474: 458,
 475: 459,
 476: 460,
 477: 461,
 478: 462,
 479: 463,
 480: 464,
 481: 465,
 482: 466,
 483: 467,
 484: 468,
 485: 469,
 486: 470,
 487: 471,
 488: 472,
 489: 473,
 490: 474,
 491: 475,
 492: 476,
 493: 477,
 494: 478,
 495: 479,
 496: 480,
 497: 481,
 498: 482,
 499: 483,
 500: 484,
 501: 485,
 502: 486,
 504: 487,
 505: 488,
 506: 489,
 515: 490,
 516: 491,
 517: 492,
 518: 493,
 519: 494,
 520: 495,
 521: 496,
 522: 497,
 523: 498,
 524: 499,
 525: 500,
 526: 501,
 527: 502,
 528: 503,
 529: 504,
 530: 505,
 533: 506,
 534: 507,
 540: 508,
 541: 509,
 542: 510,
 543: 511,
 544: 512,
 545: 513,
 546: 514,
 547: 515,
 548: 516,
 549: 517,
 550: 518,
 551: 519,
 552: 520,
 553: 521,
 554: 522,
 555: 523,
 556: 524,
 557: 525,
 558: 526,
 559: 527,
 560: 528,
 561: 529,
 562: 530,
 563: 531,
 564: 532,
 565: 533,
 566: 534,
 567: 535,
 568: 536,
 569: 537,
 570: 538,
 571: 539,
 572: 540,
 573: 541,
 574: 542,
 575: 543,
 576: 544,
 577: 545,
 578: 546,
 579: 547,
 580: 548,
 581: 549,
 582: 550,
 583: 551,
 584: 552,
 585: 553,
 586: 554,
 587: 555,
 588: 556,
 589: 557,
 590: 558,
 591: 559,
 592: 560,
 593: 561,
 594: 562,
 595: 563,
 596: 564,
 597: 565,
 598: 566,
 599: 567,
 600: 568,
 601: 569,
 602: 570,
 603: 571,
 604: 572,
 605: 573,
 606: 574,
 607: 575,
 608: 576,
 609: 577,
 610: 578,
 611: 579,
 612: 580,
 613: 581,
 614: 582,
 615: 583,
 616: 584,
 617: 585,
 618: 586,
 619: 587,
 620: 588,
 621: 589,
 622: 590,
 623: 591,
 624: 592,
 625: 593,
 626: 594,
 627: 595,
 628: 596,
 629: 597,
 630: 598,
 631: 599,
 632: 600,
 633: 601,
 634: 602,
 635: 603,
 636: 604,
 637: 605,
 638: 606,
 639: 607,
 640: 608,
 641: 609,
 642: 610,
 643: 611,
 644: 612,
 645: 613,
 646: 614,
 647: 615,
 648: 616,
 649: 617,
 650: 618,
 651: 619,
 652: 620,
 653: 621,
 654: 622,
 655: 623,
 656: 624,
 657: 625,
 658: 626,
 659: 627,
 660: 628,
 661: 629,
 662: 630,
 663: 631,
 664: 632,
 665: 633,
 666: 634,
 667: 635,
 668: 636,
 669: 637,
 670: 638,
 671: 639,
 672: 640,
 673: 641,
 674: 642,
 675: 643,
 676: 644,
 677: 645,
 678: 646,
 679: 647,
 680: 648,
 681: 649,
 682: 650,
 683: 651,
 684: 652,
 685: 653,
 686: 654,
 687: 655,
 688: 656,
 689: 657,
 690: 658,
 691: 659,
 692: 660,
 693: 661,
 694: 662,
 695: 663,
 696: 664,
 697: 665,
 698: 666,
 699: 667,
 700: 668,
 701: 669,
 702: 670,
 703: 671,
 704: 672,
 705: 673,
 706: 674,
 707: 675,
 708: 676,
 709: 677,
 710: 678,
 711: 679,
 712: 680,
 713: 681,
 714: 682,
 715: 683,
 716: 684,
 717: 685,
 718: 686,
 719: 687,
 720: 688,
 721: 689,
 722: 690,
 723: 691,
 724: 692,
 725: 693,
 726: 694,
 727: 695,
 728: 696,
 729: 697,
 730: 698,
 731: 699,
 732: 700,
 733: 701,
 734: 702,
 735: 703,
 736: 704,
 737: 705,
 738: 706,
 739: 707,
 740: 708,
 741: 709,
 742: 710,
 743: 711,
 744: 712,
 745: 713,
 746: 714,
 747: 715,
 748: 716,
 749: 717,
 750: 718,
 751: 719,
 752: 720,
 753: 721,
 754: 722,
 755: 723,
 756: 724,
 757: 725,
 758: 726,
 759: 727,
 760: 728,
 761: 729,
 762: 730,
 763: 731,
 764: 732,
 765: 733,
 766: 734,
 767: 735,
 768: 736,
 769: 737,
 770: 738,
 771: 739,
 772: 740,
 773: 741,
 774: 742,
 775: 743,
 776: 744,
 777: 745,
 778: 746,
 779: 747,
 780: 748,
 781: 749,
 782: 750,
 783: 751,
 784: 752,
 785: 753,
 786: 754,
 787: 755,
 788: 756,
 789: 757,
 790: 758,
 791: 759,
 792: 760,
 793: 761,
 794: 762,
 795: 763,
 796: 764,
 797: 765,
 798: 766,
 799: 767,
 800: 768,
 801: 769,
 802: 770,
 803: 771,
 804: 772,
 805: 773,
 806: 774,
 807: 775,
 808: 776,
 809: 777,
 810: 778,
 811: 779,
 812: 780,
 813: 781,
 814: 782,
 815: 783,
 816: 784,
 817: 785,
 818: 786,
 819: 787,
 820: 788,
 821: 789,
 822: 790,
 823: 791,
 824: 792,
 825: 793,
 826: 794,
 827: 795,
 828: 796,
 829: 797,
 830: 798,
 831: 799,
 832: 800,
 833: 801,
 834: 802,
 835: 803,
 836: 804,
 837: 805,
 838: 806,
 839: 807,
 840: 808,
 841: 809,
 842: 810,
 843: 811,
 844: 812,
 845: 813,
 846: 814,
 847: 815,
 848: 816,
 849: 817,
 850: 818,
 851: 819,
 852: 820,
 853: 821,
 854: 822,
 855: 823,
 856: 824,
 857: 825,
 858: 826,
 859: 827,
 860: 828,
 861: 829,
 862: 830,
 863: 831,
 864: 832,
 865: 833,
 866: 834,
 867: 835,
 868: 836,
 869: 837,
 870: 838,
 871: 839,
 872: 840,
 873: 841,
 874: 842,
 875: 843,
 876: 844,
 877: 845,
 878: 846,
 879: 847,
 880: 848,
 881: 849,
 882: 850,
 883: 851,
 884: 852,
 885: 853,
 886: 854,
 887: 855,
 888: 856,
 889: 857,
 890: 858,
 891: 859,
 892: 860,
 893: 861,
 894: 862,
 895: 863,
 896: 864,
 897: 865,
 898: 866,
 899: 867,
 900: 868,
 901: 869,
 902: 870,
 903: 871,
 904: 872,
 905: 873,
 906: 874,
 907: 875,
 908: 876,
 909: 877,
 910: 878,
 911: 879,
 912: 880,
 913: 881,
 914: 882,
 915: 883,
 916: 884,
 917: 885,
 918: 886,
 919: 887,
 920: 888,
 921: 889,
 922: 890,
 923: 891,
 924: 892,
 925: 893,
 926: 894,
 927: 895,
 928: 896,
 929: 897,
 930: 898,
 931: 899,
 932: 900,
 933: 901,
 934: 902,
 935: 903,
 936: 904,
 937: 905,
 938: 906,
 939: 907,
 940: 908,
 941: 909,
 942: 910,
 943: 911,
 944: 912,
 945: 913,
 946: 914,
 947: 915,
 948: 916,
 949: 917,
 950: 918,
 951: 919,
 952: 920,
 953: 921,
 954: 922,
 955: 923,
 956: 924,
 957: 925,
 958: 926,
 959: 927,
 960: 928,
 961: 929,
 962: 930,
 963: 931,
 964: 932,
 965: 933,
 966: 934,
 967: 935,
 968: 936,
 969: 937,
 970: 938,
 971: 939,
 972: 940,
 973: 941,
 974: 942,
 975: 943,
 976: 944,
 977: 945,
 978: 946,
 979: 947,
 980: 948,
 981: 949,
 982: 950,
 983: 951,
 984: 952,
 985: 953,
 986: 954,
 987: 955,
 988: 956,
 989: 957,
 990: 958,
 991: 959,
 992: 960,
 993: 961,
 994: 962,
 995: 963,
 996: 964,
 997: 965,
 998: 966,
 999: 967,
 1000: 968,
 1001: 969,
 1002: 970,
 1003: 971,
 1004: 972,
 1005: 973,
 1006: 974,
 1007: 975,
 1008: 976,
 1009: 977,
 1010: 978,
 1011: 979,
 1012: 980,
 1013: 981,
 1014: 982,
 1015: 983,
 1016: 984,
 1017: 985,
 1018: 986,
 1019: 987,
 1020: 988,
 1021: 989,
 1022: 990,
 1023: 991,
 1024: 992,
 1025: 993,
 1026: 994,
 1027: 995,
 1028: 996,
 1029: 997,
 1030: 998,
 1031: 999,
 ...}

In [8]:
print(max(mapping_R_rev.keys()))
print(max(mapping_R_rev.values()))

1700366
1597214

In [9]:
df_review_ok = df_review[df_review['unique_id'].isin(mapping_R_rev.keys())].copy()
df_review_ok['unique_id'] = df_review_ok['unique_id'].map(mapping_R_rev)
df_review_ok = df_review_ok[['unique_id', 'review_text']]
df_review_ok.tail()

         unique_id review_text
1700362    1597210        None
1700363    1597211        None
1700364    1597212        None
1700365    1597213        None
1700366    1597214        None

In [10]:
df_result = df_UR.merge( #preso da sopra
    df_review_ok,
    left_on='unique_id_review',
    right_on='unique_id',
    how='left'
)

df_result = df_result.drop(columns=['unique_id'])
#df_result = df_result[['unique_id_user', 'review_text']]
df_result.to_parquet(os.path.join(subset_dir, "competitors", "user_reviews_text.parquet"), index=False)
df_result.head()

,unique_id_user,unique_id_review,review_text
0,1094,0,Paese di montagna con boschi di faggi e castag...
1,3508,1,"Paese caratteristico con tanto da visitare,il ..."
2,2174,2,Concerto Gospel del 23/12/2021\nOrganizzato da...
3,2743,3,Piccolo borgo appollaiato tra i monti lucani.\...
4,2812,4,"Bel paese, ora con il ponte tibetano potrebbe ..."

In [11]:
df_gt.head()

,unique_id_user,animal_lover,beach_person,cultured,curious,disorganized,explorer,family_oriented,genZ,digital_nomad,lazy,romantic,free_spirit,business_traveler,online_traveler,eco_traveler
0,0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,2,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0
3,3,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0
4,4,0.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0

In [9]:
# IMAGES

#df = pd.read_parquet(os.path.join(edges_dir, "poi_has_main_image_image.parquet")) #stessi ids, non serve
df_UP = pd.read_parquet(os.path.join(edges_dir, "user_visited_poi.parquet")) #stessi ids, non serve
df_UP.head()

   unique_id_user  unique_id_poi
0            1094           4528
1            3508           4528
2            2174           4528
3            2743           4528
4            2812           4528

In [8]:
df_I = pd.read_parquet(os.path.join(nodes_dir, "image.parquet"))
df_I.head()

   unique_id                               main_image_embedding
0          0  [-0.19753423, 0.22135854, 0.1589038, -0.080560...
1          1  [0.46170676, 0.29732698, 0.17882484, -0.351835...
2          2  [-0.14220355, -0.040702403, -0.09907015, -0.24...
3          3  [-0.109207876, 0.08907696, -0.011386456, -0.04...
4          4  [-0.23309213, 0.26094317, 0.0034338012, -0.168...

In [10]:
df_result = df_UP.merge( #preso da sopra
    df_I,
    left_on='unique_id_poi',
    right_on='unique_id',
    how='left'
)

df_result = df_result.drop(columns=['unique_id'])
df_result.to_parquet(os.path.join(subset_dir, "competitors", "user_images_embs.parquet"), index=False)
df_result.head()

,unique_id_user,unique_id_poi,main_image_embedding
0,1094,4528,"[-0.07766977, 0.3793653, -0.012538094, -0.0381..."
1,3508,4528,"[-0.07766977, 0.3793653, -0.012538094, -0.0381..."
2,2174,4528,"[-0.07766977, 0.3793653, -0.012538094, -0.0381..."
3,2743,4528,"[-0.07766977, 0.3793653, -0.012538094, -0.0381..."
4,2812,4528,"[-0.07766977, 0.3793653, -0.012538094, -0.0381..."

In [15]:
#df_final = df_gt.merge(df_liliana_grouped_by_users, on="unique_id_user", how="left")
#df_final.head()
#df_final.to_parquet(os.path.join(subset_dir, "competitors", "user_reviews_text_gt.parquet"), index=False)